### PR TITLE
Implement GF2^n for arbitrary n

### PR DESCRIPTION
**Pull request by infinity0**
This allows splitting whole strings as a single unit rather than doing it
per-byte, and can help detect corrupted shares - 1 byte corrupted will cause
the recombined secret to be completely different.

Includes extra checks in {unshare,extend}* that the input shares have unique x

### CODE REVIEW

**Comment by reynir** [comment]
I implemented some checks in the `checks` branch which I didn't merge. Sorry about that. (I'm still reviewing)

**Comment by infinity0** [comment]
I've pushed your extra changes in branch "pr6" into this PR too

**Comment by reynir** [comment]
`Z.of_bits` and `Z.to_bits` is little endian. There are big endian version in `Nocrypto.Numeric.Z`. I would expect ssss etc. to use big endian.

**Comment by infinity0** [comment]
ssss amazingly seems to be host-endian, it calls [mpz_import](https://gmplib.org/manual/Integer-Import-and-Export.html) with an [endian param of 0](https://sources.debian.org/src/ssss/0.5-4/ssss.c/#L137). It also applies some scrambling ("diffusion layer") [to each mpz](https://sources.debian.org/src/ssss/0.5-4/ssss.c/#L310) for some reason, which we haven't implemented here.

For these reasons I don't think it's worth it to maintain compatibility with ssss.

**Comment by infinity0** [comment]
Ping? :)

**Pull request merged**
